# Generated by Django 4.1.4 on 2022-12-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryID', models.AutoField(db_column='categoryID', primary_key=True, serialize=False)),
                ('categoryName', models.CharField(db_column='categoryName', max_length=100, unique=True)),
                ('categoryDiscription', models.CharField(db_column='categoryDiscription', max_length=200)),
            ],
        ),
    ]
